config/routes.rb
Truestory::Application.routes.draw do

  devise_for :users

  resources :stories do
    resources :favors, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end  

  get "welcome/index"

  get "welcome/about"

  root to: 'stories#index'

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
  attr_accessible :body
end

app/models/favor.rb
class Favor < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  attr_accessible :story
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :body, :title, :user
  has_many :comments
  has_many :favors, dependent: :destroy
  has_many :votes, dependent: :destroy
  belongs_to :user
  default_scope { order('created_at DESC') }

  def points
    self.votes.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :stories
  has_many :favors, dependent: :destroy
  has_many :votes, dependent: :destroy

  def role?(base_role)
    role == base_role.to_s
  end

  def favored(story)
    self.favors.where(story_id: story.id).first
  end 

  def voted(story)
    self.votes.where(story_id: story.id).first
  end 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  attr_accessible :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protect_from_forgery
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    favor = current_user.favors.build(story: @story)

    if favor.save
      flash[:notice] = "Favored story"
      redirect_to [@story]
    else
      flash[:error] = "Unable to add favor. Please try again."
      redirect_to [@story]
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    @favor = current_user.favors.find(params[:id])

    if @favor.destroy
      flash[:notice] = "Removed favor."
      redirect_to [@story]
    else
      flash[:error] = "Unable to remove favor. Please try again."
      redirect_to [@story]
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
    authorize @story
  end

  def create
    @story = current_user.stories.new(params[:story])
    authorize @story
    if @story.save
      flash[:notice] = "Story was published!"
      redirect_to @story
    else
      flash[:error] = "There was an error. Try again."
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      flash[:notice] = "Story was updated."
      redirect_to @story
    else
      flash[:error] = "There was an error saving the story. Please try again."
      render :edit
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    vote = current_user.votes.build(story: @story)

    if vote.save
      flash[:notice] = "You believe this is a true story."
      redirect_to [@story]
    else
      flash[:error] = "There is an error."
      redirect_to [@story]
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    @vote = current_user.votes.find(params[:id])

    if @vote.destroy
      flash[:notice] = "You don't believe this is a true story!"
      redirect_to [@story]
    else
      flash[:error] = "There is an error."
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favors/_favor.html.erb
<div class="favor">
  <% if favor = current_user.favored(@story) %>
    <%= link_to [@story, favor], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; UnFavor
    <% end %>
  <% else %>
    <%= link_to [@story, Favor.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Favor
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truestory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
           Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/stories/edit.html.erb
<h1>Write Your Story</h1>

<div class="row">
  <div class="span6">
    <p>Guidelines for new story:</p>
    <ul>
      <li>Tell Your Story Here!</li>
      <li>Story should be more than 140 words.</li>
      <li>You should be honest! Tell a true story!</li>
      <li>Story should be interesting</li>
    </ul>
  </div>
  <div class="span6">
    <%= form_for @story, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/index.html.erb
<h1>All Stories</h1>
<% @stories.each do |story| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to story.title, story %>
      </h4>
      <small>
        Written <%= time_ago_in_words(story.created_at) %> ago by <%= story.user.name %><br/>
        <%= story.comments.count %> Comments
      </small>
    </div>
  </div>
<% end %>

app/views/stories/new.html.erb
<h1>Write Your Story</h1>

<div class="row">
  <div class="span6">
    <p>Guidelines for new story:</p>
    <ul>
      <li>Tell Your Story Here!</li>
      <li>Story should be more than 140 words.</li>
      <li>You should be honest! Tell a true story!</li>
      <li>Story should be interesting</li>
    </ul>
  </div>
  <div class="span6">
    <%= form_for @story, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<%= link_to "Edit", edit_story_path(@story), class: 'btn btn-mini' %>
<p><%= @story.body %></p>
<div class="row">
  <div class="span2">
    <%= render partial: 'favors/favor', local: {story: @story} %>
  </div>

  <div class="span2">
    <%= render partial: 'votes/vote', local: {story: @story} %>
  </div>
</div>

app/views/votes/_vote.html.erb
<div class="row">
  
  <div class="span2">
    
  <% if vote = current_user.voted(@story) %>
    <%= link_to [@story, vote], class: 'btn btn-primary', method: :delete do %>
      <i class="fa fa-thumbs-up"></i>TrueStory
    <% end %>
  <% else %>
    <%= link_to [@story, Vote.new], class: 'btn btn-primary', method: :post do %>
      <i class="fa fa-thumbs-up"> </i>&nbsp; TrueStory
    <% end %>
  <% end %>
  <strong><%= @story.points %></strong>
  </div> 
</div>

app/views/welcome/about.html.erb
<h1>About TrueStory</h1>
<p>Created by: Tiyang Lou</p>

app/views/welcome/index.html.erb
<h1>Welcome to TrueStory</h1>
<p>This is the homepage for TrueStory</p>